### ISSUE TITLE
Contentful Structure

### ISSUE THREAD

**Issue by ciampo** [ciampo/offbeat-appetite#1]
### post content types:

- [x] rich text
- [x] media gallery
  - [x] media object (video/image + optional caption)
- [x] recipe block
  - [x] ingredients list (name, quantity, unit)
  - [x] time (minutes)
  - [x] method

### category
 - [x] category

### tags
- [x] tag

### post
- [x] meta
- [x] slug
- [x] category
- [x] tags
- [x] content blocks
- [x] comments enabled
- [x] featured
- [x] "preview" content (content used to show a post "tile")

### pages:
- [x] home
- [x] all recipes
- [x] all stories
- [x] all toolkits
- [x] all reviews
- [x] about
- [x] single block post
- [x] search
- [x] photos

Misc:
- [x]  nav / footer / any misc piece of text

**Comment by mctonna** [comment]
Reference here for metric system conversions: https://pinchofnom.com/recipes/kfc-rice-box/
This is a British blog that allows for conversions to imperial + scaling. She uses teaspoons in both cases and they scale.
