### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by ciampo** [ciampo/offbeat-appetite#20]
- [x] hero (tagline and image)
- [x] blurb / subscription (optional)
- [x] 3 featured recipes
- [x] 1 featured stories
- [x] 3 featured reviews
- [x] 1 featured toolkits

**Comment by mctonna** [comment]
Best to have a rectangular tile image with either text beneath to avoid spoiling image. Alternatively,  text over image but image darkens when mouse hovers over image.
