### ISSUE TITLE
[UX] "Pin picture" Pinterest button

### ISSUE THREAD

**Issue by mctonna** [ciampo/offbeat-appetite#29]
It would be good to have the option as readers like to Pin.

**Comment by mctonna** [comment]
Also found this from a tutorial: 

_It’s important that once you have a Business Pinterest account, that you verify your website.

This is easy to do as long as you have the Yoast SEO plugin installed on your blog.

Go to social > Pinterest.

On Pinterest click on the verify button and grab the HTML code and place it in the box in Yoast on your blog._

**Comment by ciampo** [comment]
Reference Pinterest APIs https://developers.pinterest.com/docs/widgets/save/?
